FROM node as build
WORKDIR /app
COPY package.json .
RUN npm install --force
COPY . .
ENV REACT_APP_NAME=myName
RUN npm run build
FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]